# Generated by Django 2.2.3 on 2019-08-08 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('friends', models.IntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.SocialNetwork')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('shares', models.IntegerField(default=0)),
                ('create_date', models.DateField()),
                ('favorite', models.IntegerField(default=0)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.SocialNetwork')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Platform')),
                ('topics', models.ManyToManyField(to='post.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.User')),
            ],
        ),
    ]
