# Generated by Django 2.2.3 on 2019-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190911_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
