# Generated by Django 2.2.3 on 2019-10-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190926_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='language',
            field=models.CharField(default='es', max_length=25),
        ),
    ]
